# Set the directory for this project so make deploy need not receive PROJECT_DIR
PROJECT_DIR         := ether-cron
PROJECT_GROUP_ID    := dev.rafex.ether.cron
PROJECT_ARTIFACT_ID := ether-cron

# Include shared build logic
include ../build-helpers/common.mk
include ../build-helpers/git.mk
