---
name: "Java Publish Template"

on:
  workflow_call:
    inputs:
      module-path:
        description: "Ruta del módulo Java a compilar y desplegar"
        required: true
        type: string
      skip-tests:
        description: "Omitir tests"
        required: false
        type: boolean
        default: false
      run-deploy:
        description: "Flag to control whether the deploy step runs"
        required: false
        type: boolean
        default: true
      version:
        description: "Versión del módulo"
        required: false
        type: string
      java-distribution:
        description: "Java distribution to use (default: temurin)"
        required: false
        type: string
        default: 'temurin'
      java-version:
        description: "Java version to use (default: 21)"
        required: false
        type: string
        default: '21'
    secrets:
      OSSRH_USERNAME:
        required: true
      OSSRH_PASSWORD:
        required: true
      GPG_PRIVATE_KEY_B64:
        required: true
      MAVEN_GPG_PASSPHRASE:
        required: true

jobs:
  publish:
    if: ${{ inputs.run-deploy }}
    name: Publish ${{ inputs.module-path }}
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Generate .env for Makefile
        run: |
          # Read secrets into variables
          OSSRH_USERNAME="${{ secrets.OSSRH_USERNAME }}"
          OSSRH_PASSWORD="${{ secrets.OSSRH_PASSWORD }}"
          MAVEN_GPG_PASSPHRASE="${{ secrets.MAVEN_GPG_PASSPHRASE }}"

          # Validate
          if [ -z "$OSSRH_USERNAME" ] || [ -z "$OSSRH_PASSWORD" ] || [ -z "$MAVEN_GPG_PASSPHRASE" ]; then
            echo "⚠️ One or more required secrets are empty:"
            echo "  OSSRH_USERNAME length: ${#OSSRH_USERNAME}"
            echo "  OSSRH_PASSWORD length: ${#OSSRH_PASSWORD}"
            echo "  MAVEN_GPG_PASSPHRASE length: ${#MAVEN_GPG_PASSPHRASE}"
            exit 1
          fi

          # Generate .env
          cd ${{ inputs.module-path }}
          echo "OSSRH_USERNAME=$OSSRH_USERNAME" > .env
          echo "OSSRH_PASSWORD=$OSSRH_PASSWORD" >> .env
          echo "MAVEN_GPG_PASSPHRASE=$MAVEN_GPG_PASSPHRASE" >> .env

      - name: Import GPG private key
        env:
          GPG_PRIVATE_KEY_B64: ${{ secrets.GPG_PRIVATE_KEY_B64 }}
        run: |
          echo "$GPG_PRIVATE_KEY_B64" | base64 --decode | gpg --batch --import
          gpg --list-secret-keys

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          cache: 'maven'

      - name: Deploy via Makefile
        run: |
          cd ${{ inputs.module-path }}
          make deploy VERSION=${{ inputs.version }} SKIP_TESTS=${{ inputs.skip-tests }}
