---
name: Publish All Java Modules

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*'

jobs:
  publish-ether-parent:
    uses: ./.github/workflows/maven-central-publish-template.yml
    with:
      module-path: ether-parent/ether-parent
      release-version: ${{ github.ref_name }}
      development-version: "${{ github.ref_name }}.1-SNAPSHOT"
