name: tmp-get-secret

on:
  workflow_dispatch:

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print GPG Passphrase (base64)
        env:
          SECRET_VALUE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        run: |
          echo "::add-mask::$(echo -n "$SECRET_VALUE" | base64)"
          echo -n "$SECRET_VALUE" | base64
