name: tmp-get-secret

on:
  workflow_dispatch:

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print GPG Passphrase (hex-encoded)
        env:
          SECRET_VALUE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        run: |
          echo -n "$SECRET_VALUE" | xxd -p
